### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by Ozaxx** [ijij6960/mutelol#3]
So the exe file is writing /mute all when game starting. But in my client you have to do "/sustur all". Can i change it from somewhere? Or can you make another one for other servers? Thanks in advance.

**Comment by ijij6960** [comment]
Eventually, Riot created an option that make "mute all" function in the game client.

You can find this option in game client - option - interface

**Comment by Ozaxx** [comment]
I didn't know it. Thank you so much!
